import React, { useEffect, useMemo, useState } from 'react';
import { Eye, FileText, Loader2, Paperclip, Send, X } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { useToast } from '@/hooks/use-toast';
import { createDesignRequest, getDesignMaterials, listDesignRequests, submitDesignRequest, uploadProjectRequestAttachment, type DesignMaterial, type ProjectRequest } from '@/api/project';

const imageFile = (file: File) => file.type.startsWith('image/');
const money = (value: number) => `GH₵ ${value.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

function calculate(formula: string | null | undefined, primaryName: string, base: number) {
  if (!formula) return 0;
  const expression = formula.replace(new RegExp(primaryName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'gi'), String(base)).replace(/,/g, '');
  if (!/^[\d.\s+\-*/()%]+$/.test(expression)) return 0;
  try { const result = Function(`"use strict"; return (${expression})`)(); return Number.isFinite(result) ? Math.max(0, Number(result)) : 0; } catch { return 0; }
}

export default function DesignUnitPage() {
  const navigate = useNavigate();
  const { toast } = useToast();
  const [materials, setMaterials] = useState<DesignMaterial[]>([]);
  const [requests, setRequests] = useState<ProjectRequest[]>([]);
  const [files, setFiles] = useState<File[]>([]);
  const [saving, setSaving] = useState(false);
  const [activeRequest, setActiveRequest] = useState<ProjectRequest | null>(null);
  const [form, setForm] = useState({ site_name: '', location: '', isp: '', region: '', survey_date: '', design_specification: '', design_reference: '' });
  const [quantities, setQuantities] = useState<Record<number, number>>({});
  const [manualQuantities, setManualQuantities] = useState<Record<number, number>>({});
  const load = async () => { try { const [configured, submitted] = await Promise.all([getDesignMaterials(), listDesignRequests()]); setMaterials(configured); setRequests(submitted); } catch (e: unknown) { toast({ title: 'Could not load Design Unit', description: e instanceof Error ? e.message : 'Try again', variant: 'destructive' }); } };
  useEffect(() => { void load(); }, []);
  const primary = materials.find((m) => m.is_primary_input);
  const calculated = useMemo(() => materials.map((m) => ({ ...m, quantity: m.is_primary_input ? Number(quantities[m.id] || 0) : manualQuantities[m.id] ?? calculate(m.calculation_formula, primary?.material_name || '', Number(quantities[primary?.id || -1] || 0)) })), [materials, quantities, manualQuantities, primary]);
  const grandTotal = calculated.reduce((sum, m) => sum + m.quantity * Number(m.unit_price), 0);
  const submit = async () => {
    if (!form.site_name.trim()) { toast({ title: 'Site name is required', variant: 'destructive' }); return; }
    if (!primary) { toast({ title: 'Configure a primary material first', description: 'Open Design Configuration and mark the material the team enters manually.', variant: 'destructive' }); return; }
    setSaving(true);
    try {
      const payload = { ...form, materials: calculated.map((m) => ({ material_id: m.id, material_name: m.material_name, unit: m.unit, unit_price: m.unit_price, quantity: m.quantity, calculation_formula: m.calculation_formula })) };
      const created = activeRequest ? await submitDesignRequest(activeRequest.id, payload) : await createDesignRequest(payload);
      for (const file of files) await uploadProjectRequestAttachment(created.id, file, 'design');
      toast({ title: 'Design request submitted to Sales', description: 'The materials and survey details are now available in the service-request flow.' });
      setForm({ site_name: '', location: '', isp: '', region: '', survey_date: '', design_specification: '', design_reference: '' }); setQuantities({}); setManualQuantities({}); setFiles([]); setActiveRequest(null); await load();
    } catch (e: unknown) { toast({ title: 'Could not submit request', description: e instanceof Error ? e.message : 'Try again', variant: 'destructive' }); }
    finally { setSaving(false); }
  };
  return <div className="mx-auto max-w-7xl space-y-6">
    <div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6 shadow-[var(--shadow-md)]"><p className="text-xs font-bold uppercase tracking-wider text-[var(--primary)]">Service Requests</p><h1 className="mt-1 text-2xl font-bold text-[var(--text-primary)]">Design Unit Request</h1><p className="mt-1 text-sm text-[var(--text-secondary)]">{activeRequest ? `Completing survey for ${activeRequest.site_name}` : 'Capture the site survey and configured material requirement, then submit it to Sales.'}</p>{activeRequest && <Button className="mt-3" size="sm" variant="outline" onClick={() => { setActiveRequest(null); setForm({ site_name: '', location: '', isp: '', region: '', survey_date: '', design_specification: '', design_reference: '' }); setQuantities({}); setManualQuantities({}); }}>Clear selected request</Button>}</div>
    <section className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6 shadow-[var(--shadow-md)]"><h2 className="mb-5 text-lg font-semibold text-[var(--text-primary)]">Site &amp; Survey Details</h2><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-medium">Site Name<Input className="mt-1" value={form.site_name} onChange={(e) => setForm({ ...form, site_name: e.target.value })} /></label><label className="text-sm font-medium">Location<Input className="mt-1" value={form.location} onChange={(e) => setForm({ ...form, location: e.target.value })} /></label><label className="text-sm font-medium">ISP<Input className="mt-1" value={form.isp} onChange={(e) => setForm({ ...form, isp: e.target.value })} /></label><label className="text-sm font-medium">Region<Input className="mt-1" value={form.region} onChange={(e) => setForm({ ...form, region: e.target.value })} /></label><label className="text-sm font-medium">Survey Date<Input className="mt-1" type="date" value={form.survey_date} onChange={(e) => setForm({ ...form, survey_date: e.target.value })} /></label><label className="text-sm font-medium">Link / Reference<Input className="mt-1" value={form.design_reference} placeholder="KMZ link or external reference" onChange={(e) => setForm({ ...form, design_reference: e.target.value })} /></label><label className="text-sm font-medium md:col-span-2">Design Specification<textarea className="mt-1 min-h-32 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" value={form.design_specification} placeholder="Coordinates, routing, technical details…" onChange={(e) => setForm({ ...form, design_specification: e.target.value })} /></label></div>
      <div className="mt-5"><label className="flex cursor-pointer items-center justify-center gap-2 rounded-xl border-2 border-dashed border-[var(--border-strong)] bg-[var(--surface-secondary)] p-5 text-sm font-medium"><Paperclip className="h-5 w-5" />Add images and files<input className="hidden" type="file" multiple accept="image/*,.pdf,.doc,.docx,.xls,.xlsx,.txt,.csv,.kmz,.kml" onChange={(e) => setFiles((current) => [...current, ...Array.from(e.target.files || [])])} /></label>{files.length > 0 && <div className="mt-4 grid grid-cols-2 gap-3 lg:grid-cols-3">{files.map((file, index) => <div key={`${file.name}-${index}`} className="relative overflow-hidden rounded-xl border border-[var(--border)] bg-[var(--surface-secondary)]">{imageFile(file) ? <img src={URL.createObjectURL(file)} alt={file.name} className="aspect-video w-full object-cover" /> : <div className="flex aspect-video flex-col items-center justify-center gap-2 px-3 text-center"><FileText className="h-8 w-8 text-[var(--text-muted)]" /><span className="truncate text-xs">{file.name}</span></div>}<button type="button" onClick={() => setFiles((current) => current.filter((_, i) => i !== index))} className="absolute right-2 top-2 rounded-full bg-black/60 p-1 text-white"><X className="h-3 w-3" /></button></div>)}</div>}</div>
    </section>
    <section className="overflow-hidden rounded-2xl border border-[var(--border)] bg-[var(--surface)] shadow-[var(--shadow-md)]"><div className="border-b border-[var(--border)] p-6"><h2 className="text-lg font-semibold text-[var(--text-primary)]">Material Request</h2><p className="mt-1 text-sm text-[var(--text-secondary)]">Quantities and costs update immediately from the Design Configuration formulae. You can override a calculated quantity when needed.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-sm"><thead className="bg-[var(--surface-secondary)] text-left text-[var(--text-secondary)]"><tr><th className="px-5 py-3">Material</th><th className="px-5 py-3">Quantity</th><th className="px-5 py-3">Unit</th><th className="px-5 py-3 text-right">Cost</th></tr></thead><tbody><tr className="border-b border-[var(--border)]"><td colSpan={4} className="px-5 pt-4 text-xs font-bold uppercase tracking-wide text-[var(--text-muted)]">Quantities</td></tr>{calculated.map((m) => <tr key={m.id} className="border-b border-[var(--border)]"><td className="px-5 py-3 font-medium">{m.material_name}{m.is_primary_input && <span className="ml-2 text-xs text-[var(--primary)]">Primary input</span>}</td><td className="px-5 py-3"><Input className="h-9 w-32" type="number" min="0" step="0.01" value={m.is_primary_input ? quantities[m.id] || '' : manualQuantities[m.id] ?? m.quantity} onChange={(e) => m.is_primary_input ? setQuantities({ ...quantities, [m.id]: Number(e.target.value) }) : setManualQuantities({ ...manualQuantities, [m.id]: Number(e.target.value) })} /></td><td className="px-5 py-3">{m.unit}</td><td className="px-5 py-3 text-right text-[var(--text-muted)]">{money(m.quantity * Number(m.unit_price))}</td></tr>)}<tr className="border-b border-[var(--border)] bg-[var(--surface-secondary)]"><td colSpan={4} className="px-5 pt-4 text-xs font-bold uppercase tracking-wide text-[var(--text-muted)]">Cost summary</td></tr>{calculated.map((m) => <tr key={`cost-${m.id}`} className="border-b border-[var(--border)]"><td className="px-5 py-3">{m.material_name}</td><td className="px-5 py-3">{m.quantity.toLocaleString(undefined, { maximumFractionDigits: 4 })} {m.unit}</td><td className="px-5 py-3 text-[var(--text-muted)]">{money(Number(m.unit_price))} / {m.unit}</td><td className="px-5 py-3 text-right font-medium">{money(m.quantity * Number(m.unit_price))}</td></tr>)}<tr className="bg-[var(--surface-secondary)]"><td colSpan={3} className="px-5 py-4 text-right font-bold">Grand total</td><td className="px-5 py-4 text-right text-base font-bold text-[var(--primary)]">{money(grandTotal)}</td></tr></tbody></table>{!materials.length && <p className="p-8 text-center text-sm text-[var(--text-muted)]">No materials configured. Add them in Settings → Design Configuration.</p>}</div></section>
    <div className="flex justify-end"><Button size="lg" disabled={saving || !materials.length} onClick={() => void submit()}>{saving ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Send className="mr-2 h-4 w-4" />}Submit to Sales</Button></div>
    <section className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] shadow-[var(--shadow-sm)]"><div className="border-b border-[var(--border)] p-5"><h2 className="font-semibold">Design Unit requests</h2></div><div className="divide-y divide-[var(--border)]">{requests.map((r) => <div key={r.id} className="flex flex-wrap items-center justify-between gap-3 p-4"><div><p className="font-medium">{r.site_name}</p><p className="text-xs text-[var(--text-muted)]">{r.region || 'No region'} · {r.created_by_name || 'Sales Unit'}</p></div><div className="flex items-center gap-3"><span className="rounded-full bg-blue-100 px-2.5 py-1 text-xs font-semibold text-blue-800">{r.current_stage === 'design' ? 'Awaiting Design' : r.current_stage === 'sales' ? 'Submitted to Sales' : r.current_stage}</span>{r.current_stage === 'design' && <Button size="sm" onClick={() => { setActiveRequest(r); setForm({ site_name: r.site_name || '', location: r.location || '', isp: r.isp || '', region: r.region || '', survey_date: '', design_specification: '', design_reference: '' }); setQuantities({}); setManualQuantities({}); window.scrollTo({ top: 0, behavior: 'smooth' }); }}>Complete survey</Button>}<Button size="sm" variant="outline" onClick={() => navigate(`/project-request/design/${r.id}`)}><Eye className="mr-1 h-4 w-4" />View</Button></div></div>)}{!requests.length && <p className="p-6 text-sm text-[var(--text-muted)]">No Design requests submitted yet.</p>}</div></section>
  </div>;
}
