import React, { useCallback, useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Eye, FileText, Loader2, Plus, Search, Send } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { useToast } from '@/hooks/use-toast';
import { createSalesRequest, listSalesRequests, salesForwardProjectRequest, type ProjectRequest } from '@/api/project';

export default function SalesUnitPage() {
  const navigate = useNavigate();
  const { toast } = useToast();
  const [requests, setRequests] = useState<ProjectRequest[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [showForm, setShowForm] = useState(false);
  const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ site_name: '', location: '', region: '', isp: '', initial_remarks: '' });
  const load = useCallback(async () => {
    try { setLoading(true); setRequests(await listSalesRequests()); }
    catch (e: unknown) { toast({ title: 'Could not load Sales requests', description: e instanceof Error ? e.message : 'Try again', variant: 'destructive' }); }
    finally { setLoading(false); }
  }, [toast]);
  useEffect(() => { void load(); }, [load]);
  const visible = requests.filter((r) => [r.site_name, r.location, r.region, r.isp, r.created_by_name].some((value) => String(value || '').toLowerCase().includes(search.toLowerCase())));
  return <div className="mx-auto max-w-7xl space-y-6">
    <div className="flex flex-wrap items-start justify-between gap-4 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6 shadow-[var(--shadow-md)]"><div><p className="text-xs font-bold uppercase tracking-wider text-[var(--primary)]">Service Requests</p><h1 className="mt-1 text-2xl font-bold text-[var(--text-primary)]">Sales Unit</h1><p className="mt-1 text-sm text-[var(--text-secondary)]">Create a request for Design, review the completed survey and materials, then forward it to Project Unit.</p></div><Button onClick={() => setShowForm((open) => !open)}><Plus className="mr-2 h-4 w-4" />New request for Design</Button></div>
    {showForm && <section className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6 shadow-[var(--shadow-sm)]"><h2 className="font-semibold text-[var(--text-primary)]">Send request to Design Unit</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="text-sm font-medium">Site name<Input className="mt-1" value={form.site_name} onChange={(e) => setForm({ ...form, site_name: e.target.value })} /></label><label className="text-sm font-medium">Location<Input className="mt-1" value={form.location} onChange={(e) => setForm({ ...form, location: e.target.value })} /></label><label className="text-sm font-medium">Region<Input className="mt-1" value={form.region} onChange={(e) => setForm({ ...form, region: e.target.value })} /></label><label className="text-sm font-medium">ISP<Input className="mt-1" value={form.isp} onChange={(e) => setForm({ ...form, isp: e.target.value })} /></label><label className="text-sm font-medium md:col-span-2">Request notes<textarea className="mt-1 min-h-24 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" value={form.initial_remarks} onChange={(e) => setForm({ ...form, initial_remarks: e.target.value })} /></label></div><div className="mt-5 flex gap-3"><Button disabled={saving} onClick={async () => { if (!form.site_name.trim()) { toast({ title: 'Site name is required', variant: 'destructive' }); return; } setSaving(true); try { await createSalesRequest(form); toast({ title: 'Sent to Design Unit' }); setForm({ site_name: '', location: '', region: '', isp: '', initial_remarks: '' }); setShowForm(false); await load(); } catch (e: unknown) { toast({ title: 'Could not send request', description: e instanceof Error ? e.message : 'Try again', variant: 'destructive' }); } finally { setSaving(false); } }}><Send className="mr-2 h-4 w-4" />Send to Design</Button><Button variant="outline" onClick={() => setShowForm(false)}>Cancel</Button></div></section>}
    <section className="overflow-hidden rounded-2xl border border-[var(--border)] bg-[var(--surface)] shadow-[var(--shadow-md)]"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-[var(--border)] p-5"><div className="flex items-center gap-2"><FileText className="h-5 w-5 text-[var(--primary)]" /><h2 className="font-semibold text-[var(--text-primary)]">Design submissions</h2></div><div className="relative w-full sm:w-72"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[var(--text-muted)]" /><Input className="pl-9" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search site, location, ISP…" /></div></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-sm"><thead className="bg-[var(--surface-secondary)] text-left text-[var(--text-secondary)]"><tr><th className="px-5 py-3">Site</th><th className="px-5 py-3">Location / Region</th><th className="px-5 py-3">Stage</th><th className="px-5 py-3">Survey date</th><th className="px-5 py-3">Submitted by</th><th className="px-5 py-3" /></tr></thead><tbody className="divide-y divide-[var(--border)]">{loading ? <tr><td colSpan={6} className="px-5 py-12 text-center"><Loader2 className="mx-auto h-6 w-6 animate-spin text-[var(--primary)]" /></td></tr> : visible.map((request) => <tr key={request.id} className="hover:bg-[var(--surface-hover)]"><td className="px-5 py-4 font-medium text-[var(--text-primary)]">{request.site_name}</td><td className="px-5 py-4">{[request.location, request.region].filter(Boolean).join(' · ') || '—'}</td><td className="px-5 py-4"><span className="rounded-full bg-blue-100 px-2 py-1 text-xs font-semibold text-blue-800">{request.current_stage === 'design' ? 'With Design' : request.current_stage === 'sales' ? 'Ready for Sales' : request.current_stage}</span></td><td className="px-5 py-4">{request.survey_date ? new Date(request.survey_date).toLocaleDateString() : '—'}</td><td className="px-5 py-4">{request.created_by_name || 'Sales Unit'}</td><td className="px-5 py-4 text-right"><div className="flex justify-end gap-2"><Button size="sm" variant="outline" onClick={() => navigate(`/project-request/sales/${request.id}`)}><Eye className="mr-1 h-4 w-4" />View</Button>{request.current_stage === 'sales' && <Button size="sm" onClick={async () => { try { await salesForwardProjectRequest(request.id); toast({ title: 'Sent to Project Unit' }); await load(); } catch (e: unknown) { toast({ title: 'Could not forward', description: e instanceof Error ? e.message : 'Try again', variant: 'destructive' }); } }}>Forward to Project</Button>}</div></td></tr>)}{!loading && !visible.length && <tr><td colSpan={6} className="px-5 py-12 text-center text-[var(--text-muted)]">No Design submissions are waiting for Sales.</td></tr>}</tbody></table></div></section>
  </div>;
}
