import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Check, Download, Eye, FileSignature, Loader2, Pencil, Plus, Printer, Search, Send, X } from 'lucide-react';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { useAuth } from '@/context/AuthContext';
import { useToast } from '@/hooks/use-toast';
import { approveSignoffForm, createSignoffForm, getSignoffForm, getSignoffLinkOptions, listSignoffForms, rejectSignoffForm, submitSignoffForm, updateSignoffForm, type SignoffForm } from '@/api/project';
import { ShareButton } from '@/components/ShareButton';
import { useSharedView } from '@/context/SharedViewContext';

const today = () => new Date().toISOString().slice(0, 10);
const manager = (u: any) => ['admin', 'superadmin', 'system_admin', 'project_manager'].includes(String(u?.main_role || u?.role || '').toLowerCase()) || String(u?.position || '').toLowerCase() === 'project manager';
const supervisor = (u: any) => !manager(u);
const systemAdmin = (u: any) => ['system_admin', 'superadmin'].includes(String(u?.main_role || u?.role || '').toLowerCase()) || String(u?.username || '').toLowerCase() === 'superadmin';
const nameOf = (u: any) => u?.full_name || [u?.first_name, u?.last_name].filter(Boolean).join(' ') || u?.username || '';
const dateText = (value?: string | null) => value ? new Date(`${value}`.slice(0, 10)).toLocaleDateString() : '—';
const statusStyle: Record<string, string> = { draft: 'bg-slate-100 text-slate-700', pending: 'bg-amber-100 text-amber-800', approved: 'bg-emerald-100 text-emerald-800', rejected: 'bg-rose-100 text-rose-800' };
const statusText: Record<string, string> = { draft: 'Draft', pending: 'Pending Manager Approval', approved: 'Approved', rejected: 'Rejected' };

function Status({ value }: { value: string }) { return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-bold ${statusStyle[value] || statusStyle.draft}`}>{statusText[value] || value}</span>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block border-b border-slate-200 p-3 text-xs font-semibold text-slate-600 last:border-b-0"><span className="mb-1 block uppercase tracking-wide">{label}</span>{children}</label>; }
function TextField({ label, value, onChange, type = 'text', readOnly = false }: any) { return <Field label={label}><Input type={type} value={value || ''} readOnly={readOnly} onChange={(e) => onChange?.(e.target.value)} className="h-8 border-0 bg-transparent px-0 text-sm text-slate-900 shadow-none focus-visible:ring-0" /></Field>; }
function SignatureInput({ value, onChange, disabled = false }: { value?: string | null; onChange: (value: string) => void; disabled?: boolean }) {
  const file = async (f?: File) => { if (!f) return; if (!f.type.startsWith('image/')) return; onChange(await new Promise<string>((resolve) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.readAsDataURL(f); })); };
  return <div className="mt-1 rounded border border-dashed border-slate-300 bg-white p-2">{value ? <img src={value} className="h-14 max-w-full object-contain object-left" alt="Signature" /> : <span className="text-xs text-slate-400">Upload signature image</span>}{!disabled && <Input className="mt-1 h-7 border-0 p-0 text-xs" type="file" accept="image/*" onChange={(e) => void file(e.target.files?.[0])} />}</div>;
}

export function SignoffFormsList() {
  const navigate = useNavigate(); const { user } = useAuth(); const [forms, setForms] = useState<SignoffForm[]>([]); const [status, setStatus] = useState('all'); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { try { setLoading(true); setForms(await listSignoffForms({ status, search })); } finally { setLoading(false); } }, [status, search]);
  useEffect(() => { void load(); }, [load]);
  return <div className="mx-auto max-w-7xl space-y-6 p-4 sm:p-7">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-emerald-700">PROJECT UNIT</p><h1 className="text-3xl font-bold tracking-tight text-slate-900">Sign-Off Forms</h1><p className="mt-1 text-sm text-slate-500">Manage project acceptance and sign-off documentation</p></div>{(supervisor(user)||systemAdmin(user)) && <Button className="gap-2 bg-emerald-700 hover:bg-emerald-800" onClick={() => navigate('/project-unit/signoff/new')}><Plus className="h-4 w-4" /> New Sign-Off Form</Button>}</div>
    <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div className="relative max-w-md flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><Input className="pl-9" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search Site Name, Circuit ID, Customer" /></div><div className="flex flex-wrap gap-1">{['all','draft','pending','approved','rejected'].map((s) => <button key={s} onClick={() => setStatus(s)} className={`rounded-full px-3 py-2 text-xs font-bold ${status === s ? 'bg-emerald-700 text-white' : 'text-slate-600 hover:bg-slate-100'}`}>{s === 'all' ? 'All' : statusText[s]}</button>)}</div></div>
      <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[840px] text-left text-sm"><thead className="border-y border-slate-100 bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{['Ref No.','Site Name','Circuit ID','Type of Service','Test Date','Billing Date','Status','Created by','Actions'].map((h) => <th key={h} className="px-3 py-3 font-semibold">{h}</th>)}</tr></thead><tbody>{loading ? <tr><td colSpan={9} className="p-10 text-center text-slate-400"><Loader2 className="mx-auto h-5 w-5 animate-spin" /></td></tr> : forms.length === 0 ? <tr><td colSpan={9} className="p-10 text-center text-slate-400">No sign-off forms match these filters.</td></tr> : forms.map((f) => <tr key={f.id} className="border-b border-slate-100 hover:bg-slate-50"><td className="px-3 py-3 font-bold text-emerald-800">{f.reference_no}</td><td className="px-3 py-3 font-medium">{f.site_name}</td><td className="px-3 py-3">{f.circuit_id || '—'}</td><td className="px-3 py-3">{f.type_of_service || '—'}</td><td className="px-3 py-3">{dateText(f.test_date)}</td><td className="px-3 py-3">{dateText(f.billing_date)}</td><td className="px-3 py-3"><Status value={f.status} /></td><td className="px-3 py-3">{f.created_by_name}</td><td className="px-3 py-3"><Button variant="ghost" size="sm" className="gap-1" onClick={() => navigate(`/project-unit/signoff/${f.id}`)}><Eye className="h-4 w-4" /> View</Button></td></tr>)}</tbody></table></div></div>
  </div>;
}

const empty = (user: any) => ({ contractor: 'Vobiss Solutions Ltd', site_name: '', vobiss_name: nameOf(user), vobiss_date: today(), status: 'draft' });
export default function SignoffFormPage() {
  const { isSharedView, routeParams } = useSharedView();
  const { id: routeId } = useParams(); const id = isSharedView ? routeParams?.id : routeId; const isNew = id === 'new'; const navigate = useNavigate(); const { user } = useAuth(); const { toast } = useToast(); const [form, setForm] = useState<any>(() => empty(user)); const [loading, setLoading] = useState(!isNew); const [saving, setSaving] = useState(false); const [approvalSignature, setApprovalSignature] = useState(''); const [rejectReason, setRejectReason] = useState(''); const [linkOptions, setLinkOptions] = useState<any>({ service_requests: [], wip_entries: [] }); const documentRef = useRef<HTMLDivElement>(null);
  const editable = !isSharedView && (isNew || ((supervisor(user) || systemAdmin(user)) && Number(form.created_by) === Number(user?.id) && ['draft','rejected'].includes(form.status))); const isManager = !isSharedView && manager(user);
  useEffect(() => { if (!isNew && id) getSignoffForm(Number(id)).then(setForm).catch((e) => toast({ title: 'Unable to load form', description: e.message, variant: 'destructive' })).finally(() => setLoading(false)); }, [id, isNew, toast]);
  useEffect(() => { void getSignoffLinkOptions().then(setLinkOptions).catch(() => undefined); }, []);
  const set = (key: string, value: any) => setForm((v: any) => ({ ...v, [key]: value }));
  const payload = useMemo(() => { const { id: _id, reference_no: _ref, status: _status, created_by: _by, created_by_name: _name, created_at: _created, updated_at: _updated, manager_signature: _ms, manager_name: _mn, manager_date: _md, rejection_reason: _rr, ...data } = form; return data; }, [form]);
  const save = async (submit = false) => { try { setSaving(true); const f = isNew ? await createSignoffForm(payload) : await updateSignoffForm(form.id, payload); const saved = submit ? await submitSignoffForm(f.id) : f; toast({ title: submit ? 'Submitted for approval' : 'Draft saved', description: submit ? 'The Project Unit Manager has been notified.' : 'Your sign-off form is safely saved.' }); navigate(submit ? '/project-unit/signoff' : `/project-unit/signoff/${saved.id}`, { replace: true }); } catch (e: any) { toast({ title: 'Could not save', description: e.message, variant: 'destructive' }); } finally { setSaving(false); } };
  const approve = async () => { if (!confirm('Are you sure you want to approve this sign-off form?')) return; try { setSaving(true); setForm(await approveSignoffForm(form.id, approvalSignature)); toast({ title: 'Sign-off form approved' }); } catch (e: any) { toast({ title: 'Approval failed', description: e.message, variant: 'destructive' }); } finally { setSaving(false); } };
  const reject = async () => { try { setSaving(true); setForm(await rejectSignoffForm(form.id, rejectReason)); toast({ title: 'Sign-off form rejected' }); } catch (e: any) { toast({ title: 'Rejection failed', description: e.message, variant: 'destructive' }); } finally { setSaving(false); } };
  const exportPdf = async () => { if (!documentRef.current) return; const canvas = await html2canvas(documentRef.current, { scale: 2, backgroundColor: '#ffffff' }); const pdf = new jsPDF('p', 'mm', 'a4'); const height = canvas.height * 190 / canvas.width; pdf.addImage(canvas.toDataURL('image/png'), 'PNG', 10, 10, 190, height); pdf.save(`${form.reference_no || 'signoff-form'}.pdf`); };
  if (loading) return <div className="p-12 text-center"><Loader2 className="mx-auto h-6 w-6 animate-spin text-emerald-700" /></div>;
  return <div className="mx-auto max-w-5xl p-4 sm:p-7"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><Link to="/project-unit/signoff" className="text-sm font-semibold text-emerald-700 hover:underline">← Sign-Off Forms</Link>{!isNew && <div className="flex gap-2">{!isSharedView && <ShareButton recordType="signoff_form" recordId={form.id} pagePath={window.location.pathname} pageTitle={`Sign-Off Form ${form.reference_no || `#${form.id}`}`} recordPreview={{ title: `Sign-Off Form ${form.reference_no || `#${form.id}`}`, reference: form.reference_no, status: form.status, site: form.site_name, circuit_id: form.circuit_id, type_of_service: form.type_of_service, contractual_bandwidth: form.contractual_bandwidth, test_date: form.test_date, packet_loss: form.packet_loss, latency: form.latency, jitter: form.jitter }} />}<Button variant="outline" size="sm" className="gap-1" onClick={() => window.print()}><Printer className="h-4 w-4" /> Print</Button><Button variant="outline" size="sm" className="gap-1" onClick={() => void exportPdf()}><Download className="h-4 w-4" /> Export PDF</Button></div>}</div>
    <div ref={documentRef} className="overflow-hidden rounded-xl border border-slate-300 bg-white shadow-sm print:shadow-none"><div className="flex items-start justify-between border-b-2 border-emerald-800 p-6"><div className="text-lg font-black tracking-tight text-emerald-800">VOBISS<span className="text-slate-900"> SOLUTIONS LTD</span></div><div className="text-center"><h1 className="text-xl font-black tracking-wider text-slate-900">SIGN-OFF FORM</h1><p className="mt-1 text-xs text-slate-500">Project Acceptance &amp; Service Commissioning</p></div><Status value={form.status || 'draft'} /></div>
      <div className="p-5 sm:p-7"><Section title="1. Project Details"><div className="grid border border-slate-200 sm:grid-cols-2"><TextField label="Contractor" value="Vobiss Solutions Ltd" readOnly /><TextField label="Site Name *" value={form.site_name} onChange={(v: string) => set('site_name', v)} readOnly={!editable} /><TextField label="Circuit ID" value={form.circuit_id} onChange={(v: string) => set('circuit_id', v)} readOnly={!editable} /><TextField label="Type of Service" value={form.type_of_service} onChange={(v: string) => set('type_of_service', v)} readOnly={!editable} /><TextField label="Contractual Bandwidth" value={form.contractual_bandwidth} onChange={(v: string) => set('contractual_bandwidth', v)} readOnly={!editable} /><TextField label="Test Date" type="date" value={form.test_date?.slice(0,10)} onChange={(v: string) => set('test_date', v)} readOnly={!editable} /><TextField label="Device Type" value={form.device_type} onChange={(v: string) => set('device_type', v)} readOnly={!editable} /><TextField label="Device Model" value={form.device_model} onChange={(v: string) => set('device_model', v)} readOnly={!editable} /><TextField label="Device Serial Number" value={form.device_serial_number} onChange={(v: string) => set('device_serial_number', v)} readOnly={!editable} /></div></Section>
        <div className="mb-6 grid border border-slate-200 sm:grid-cols-2"><Field label="Link to Service Request or WIP (optional)"><select disabled={!editable} value={form.linked_record_id ? `${form.linked_record_type}:${form.linked_record_id}` : ''} onChange={(e) => { const [type, recordId] = e.target.value.split(':'); const o = (type === 'service_request' ? linkOptions.service_requests : linkOptions.wip_entries).find((v: any) => String(v.id) === recordId); setForm((f: any) => ({ ...f, linked_record_type: type || null, linked_record_id: recordId || null, linked_record_ref: o?.reference || null })); }} className="h-8 w-full bg-transparent text-sm"><option value="">Searchable records</option><optgroup label="Service Requests">{linkOptions.service_requests.map((o: any) => <option key={`sr-${o.id}`} value={`service_request:${o.id}`}>{o.label}</option>)}</optgroup><optgroup label="WIP Entries">{linkOptions.wip_entries.map((o: any) => <option key={`wip-${o.id}`} value={`wip_entry:${o.id}`}>{o.label}</option>)}</optgroup></select></Field><TextField label="Reference / description" value={form.linked_record_ref} onChange={(v: string) => set('linked_record_ref', v)} readOnly={!editable} /></div>
        <Section title="2. Network Performance / Capacity Test"><div className="overflow-hidden border border-slate-200"><div className="grid grid-cols-2 bg-slate-100 text-xs font-bold uppercase"><div className="p-3">Test</div><div className="border-l border-slate-200 p-3">Results</div></div>{[['Packet Loss','packet_loss'],['Latency','latency'],['Jitter','jitter'],['Billing Date','billing_date']].map(([label, key]) => <div key={key} className="grid grid-cols-2 border-t border-slate-200"><div className="p-3 text-sm font-medium">{label}</div><div className="border-l border-slate-200 px-3"><Input type={key === 'billing_date' ? 'date' : 'text'} value={form[key]?.slice?.(0,10) || form[key] || ''} onChange={(e) => set(key, e.target.value)} readOnly={!editable} className="h-10 border-0 bg-transparent px-0 shadow-none focus-visible:ring-0" /></div></div>)}</div></Section>
        <Section title="3. Billing"><p className="border border-slate-200 bg-slate-50 p-4 text-sm italic text-slate-600">Billing starts after 48 hours of testing the service. This Acceptance Test does not, in any way, change any payment obligation under the agreement.</p></Section>
        <Section title="4. Signatures"><div className="grid gap-4 md:grid-cols-2"><SignatureBlock title="On behalf of Client / Customer" form={form} set={set} prefix="client" editable={editable} /><SignatureBlock title="On behalf of Vobiss Solutions Ltd" form={form} set={set} prefix="vobiss" editable={editable} /></div></Section>
        <Section title="5. Manager Approval Signature"><div className={`rounded border p-4 ${form.status === 'approved' ? 'border-emerald-200 bg-emerald-50' : 'border-slate-200 bg-slate-100 opacity-70'}`}>{form.status === 'approved' ? <div className="flex items-start justify-between gap-4"><div><p className="font-bold text-emerald-800">Approved by {form.manager_name}</p><p className="text-sm text-slate-600">Approval date: {dateText(form.manager_date)}</p>{form.manager_signature && <img src={form.manager_signature} className="mt-2 h-14 max-w-full object-contain object-left" alt="Manager signature" />}</div><span className="rotate-[-8deg] rounded border-2 border-emerald-600 px-3 py-2 text-sm font-black uppercase tracking-wider text-emerald-700">Approved</span></div> : <p className="text-sm text-slate-500">This section is locked until the Project Unit Manager approves the submitted form.</p>}</div></Section>
        {form.rejection_reason && <div className="mt-5 rounded border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800"><strong>Manager rejection reason:</strong> {form.rejection_reason}</div>}
        {form.linked_record_ref && <div className="mt-5 rounded border border-emerald-100 bg-emerald-50 p-3 text-sm"><strong>Linked record:</strong> {form.linked_record_id ? <Link className="font-semibold text-emerald-800 underline" to={form.linked_record_type === 'service_request' ? `/project-request/project/${form.linked_record_id}` : '/project-unit/wip'}>{form.linked_record_ref}</Link> : form.linked_record_ref}</div>}
        <footer className="mt-8 border-t pt-3 text-center text-xs text-slate-400">Vobiss Solutions Ltd · Sign-Off and Acceptance Documentation</footer>
      </div></div>
    {editable && <div className="mt-5 flex flex-wrap justify-end gap-2"><Button variant="outline" disabled={saving} onClick={() => void save(false)}>Save as Draft</Button><Button disabled={saving} className="gap-2 bg-emerald-700 hover:bg-emerald-800" onClick={() => void save(true)}><Send className="h-4 w-4" /> Submit for Approval</Button></div>}
    {isManager && form.status === 'pending' && <div className="mt-5 grid gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 md:grid-cols-2"><div><p className="mb-2 text-sm font-bold text-amber-900">Approve this form</p><SignatureInput value={approvalSignature} onChange={setApprovalSignature} /><Button disabled={saving || !approvalSignature} className="mt-2 gap-1 bg-emerald-700 hover:bg-emerald-800" onClick={() => void approve()}><Check className="h-4 w-4" /> Approve</Button></div><div><p className="mb-2 text-sm font-bold text-rose-900">Reject with reason</p><Input value={rejectReason} onChange={(e) => setRejectReason(e.target.value)} placeholder="Please provide a reason for rejection" /><Button disabled={saving || !rejectReason.trim()} variant="destructive" className="mt-2 gap-1" onClick={() => void reject()}><X className="h-4 w-4" /> Reject</Button></div></div>}
  </div>;
}
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="mb-6"><h2 className="mb-2 text-sm font-black uppercase tracking-wide text-slate-800">{title}</h2>{children}</section>; }
function SignatureBlock({ title, form, set, prefix, editable }: any) { return <div className="border border-slate-200 p-4"><h3 className="mb-3 text-sm font-bold text-slate-800">{title}</h3><Field label="Signature"><SignatureInput value={form[`${prefix}_signature`]} onChange={(v) => set(`${prefix}_signature`, v)} disabled={!editable} /></Field><TextField label="Name" value={form[`${prefix}_name`]} onChange={(v: string) => set(`${prefix}_name`, v)} readOnly={!editable} /><TextField label="Date" type="date" value={form[`${prefix}_date`]?.slice(0,10)} onChange={(v: string) => set(`${prefix}_date`, v)} readOnly={!editable} /><TextField label="Telephone" value={form[`${prefix}_telephone`]} onChange={(v: string) => set(`${prefix}_telephone`, v)} readOnly={!editable} />{prefix === 'client' && <TextField label="Company Name" value={form.client_company_name} onChange={(v: string) => set('client_company_name', v)} readOnly={!editable} />}</div>; }
